name: Format

on: [ push ]

jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      - name: check out source repository
        uses: actions/checkout@v3

      - name: set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: black formatting
        uses: psf/black@stable

      - name: flake8 linting
        uses: py-actions/flake8@v2

      - name: isort formatting
        uses: isort/isort-action@v1.0.0
        with:
          configuration: --profile black
